### ISSUE TITLE
Kustomize panic runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by gitbluf** [fluxcd/kustomize-controller#517]
Since recently kustomize-controller started having runtime errors:
Any advice would be appreciated.
```
{"level":"info","ts":"2021-12-10T09:41:55.457Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-12-10T09:41:55.458Z","logger":"setup","msg":"starting manager"}
I1210 09:41:55.461139       7 leaderelection.go:248] attempting to acquire leader lease flux-system/kustomize-controller-leader-election...
{"level":"info","ts":"2021-12-10T09:41:55.461Z","msg":"starting metrics server","path":"/metrics"}
^[[3~
I1210 09:42:37.952866       7 leaderelection.go:258] successfully acquired lease flux-system/kustomize-controller-leader-election
{"level":"debug","ts":"2021-12-10T09:42:37.952Z","logger":"events","msg":"Normal","object":{"kind":"ConfigMap","namespace":"flux-system","name":"kustomize-controller-leader-election","uid":"538532d1-f661-49d8-83ff-19801e36c9d5","apiVersion":"v1","resourceVersion":"8924878"},"reason":"LeaderElection","message":"kustomize-controller-8475775fcd-6lprc_abfc5081-5ff2-45a6-b398-924cd21194ee became leader"}
{"level":"debug","ts":"2021-12-10T09:42:37.953Z","logger":"events","msg":"Normal","object":{"kind":"Lease","namespace":"flux-system","name":"kustomize-controller-leader-election","uid":"d0aa6390-a625-4977-83fd-30d868366c0e","apiVersion":"coordination.k8s.io/v1","resourceVersion":"8924879"},"reason":"LeaderElection","message":"kustomize-controller-8475775fcd-6lprc_abfc5081-5ff2-45a6-b398-924cd21194ee became leader"}
{"level":"info","ts":"2021-12-10T09:42:37.953Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-12-10T09:42:37.953Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-12-10T09:42:37.953Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-12-10T09:42:37.953Z","logger":"controller.kustomization","msg":"Starting Controller","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization"}
{"level":"info","ts":"2021-12-10T09:42:38.054Z","logger":"controller.kustomization","msg":"Starting workers","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","worker count":1}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x135c722]

goroutine 341 [running]:
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.handleErr(0xc0008b9ef8)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/yaml.go:304 +0x8d
panic(0x1dd12a0, 0x31196a0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_split_stem_comment(0xc0007ea800, 0x38)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/parserc.go:789 +0x42
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_parse_indentless_sequence_entry(0xc0007ea800, 0xc0007eaab0, 0xc0008b9a88)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/parserc.go:751 +0xe5
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_state_machine(0xc0007ea800, 0xc0007eaab0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/parserc.go:185 +0x22b
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_parse(0xc0007ea800, 0xc0007eaab0, 0xc0007777c0)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/parserc.go:129 +0x95
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).peek(0xc0007ea800, 0x7)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:103 +0x45
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).sequence(0xc0007ea800, 0xc000777707)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:258 +0xe5
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0007ea800, 0xc000777720)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:154 +0xe7
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(0xc0007ea800, 0xc000776e60, 0xc000777720)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:194 +0x2f
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).mapping(0xc0007ea800, 0xc000776d09)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:285 +0x1ac
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0007ea800, 0xc000776d20)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:152 +0x10d
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(0xc0007ea800, 0xc000776320, 0xc000776d20)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:194 +0x2f
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).mapping(0xc0007ea800, 0x9)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:285 +0x1ac
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0007ea800, 0xc000000003)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:152 +0x10d
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:194
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).document(0xc0007ea800, 0x3)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:203 +0x8b
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0007ea800, 0xc0004a8850)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/decode.go:156 +0x87
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*Decoder).Decode(0xc0004d4340, 0x1ece920, 0xc0007761e0, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/internal/forked/github.com/go-yaml/yaml/yaml.go:123 +0xf5
sigs.k8s.io/kustomize/kyaml/kio.(*ByteReader).decode(0xc0008ba3b0, 0xc0004c81c0, 0x1bf, 0x0, 0xc0004d4340, 0x1c0, 0x0, 0xc0004c81c0)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/kio/byteio_reader.go:292 +0x74
sigs.k8s.io/kustomize/kyaml/kio.(*ByteReader).Read(0xc0008ba3b0, 0xc0008da6f0, 0x4eb4ef, 0xc000186700, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/kio/byteio_reader.go:228 +0x388
sigs.k8s.io/kustomize/kyaml/kio.FromBytes(0xc0001ec200, 0x1bf, 0x200, 0x1336eb5, 0xc000726ae0, 0x55, 0xc0001ec200, 0x1bf)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/kio/byteio_reader.go:110 +0xc5
sigs.k8s.io/kustomize/api/resource.(*Factory).RNodesFromBytes(0xc0009b2ee8, 0xc0001ec200, 0x1bf, 0x200, 0xc0001ec200, 0x1bf, 0x200, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.10.1/resource/factory.go:167 +0x45
sigs.k8s.io/kustomize/api/resource.(*Factory).SliceFromBytes(0xc0009b2ee8, 0xc0001ec200, 0x1bf, 0x200, 0x1bf, 0x200, 0x0, 0x0, 0xc0008ba550)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.10.1/resource/factory.go:120 +0x4d
github.com/fluxcd/kustomize-controller/controllers.(*KustomizeGenerator).generateKustomization.func1.1(0xc000726ae0, 0x55, 0x23dc018, 0xc00091e4e0, 0x0, 0x0, 0x4f046e, 0xc00091e4e0)
        /workspace/controllers/kustomization_generator.go:173 +0x193
path/filepath.walk(0xc000726ae0, 0x55, 0x23dc018, 0xc00091e4e0, 0xc000876000, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:414 +0x457
path/filepath.walk(0xc000875a00, 0x3c, 0x23dc018, 0xc00091e1a0, 0xc000876000, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc000875940, 0x35, 0x23dc018, 0xc0008d5e10, 0xc000876000, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0009254d0, 0x27, 0x23dc018, 0xc0008d5ad0, 0xc000876000, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0008f3960, 0x1f, 0x23dc018, 0xc0008d5a00, 0xc000876000, 0x0, 0x40)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.Walk(0xc0008f3960, 0x1f, 0xc000876000, 0x1, 0xc000876000)
        /usr/local/go/src/path/filepath/path.go:501 +0x113
sigs.k8s.io/kustomize/kyaml/filesys.fsOnDisk.Walk(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.0/filesys/fsondisk.go:136
github.com/fluxcd/kustomize-controller/controllers.(*KustomizeGenerator).generateKustomization.func1(0xc0008f3960, 0x1f, 0xc0008f3960, 0x1f, 0x0, 0x0, 0x0)
        /workspace/controllers/kustomization_generator.go:144 +0x108
github.com/fluxcd/kustomize-controller/controllers.(*KustomizeGenerator).generateKustomization(0xc0008bc798, 0xc0008f3960, 0x1f, 0x40dbfb, 0x18)
        /workspace/controllers/kustomization_generator.go:187 +0x225
github.com/fluxcd/kustomize-controller/controllers.(*KustomizeGenerator).WriteFile(0xc0008bc798, 0xc0008f3960, 0x1f, 0x23e9428, 0xc0003db2c0)
        /workspace/controllers/kustomization_generator.go:50 +0x5d
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).generate(...)
        /workspace/controllers/kustomization_controller.go:602
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).reconcile(0xc0007ae660, 0x23ce928, 0xc0008a45a0, 0x1c48819, 0xd, 0xc0007a5fb0, 0x23, 0xc0007a7914, 0xb, 0x0, ...)
        /workspace/controllers/kustomization_controller.go:342 +0xade
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).Reconcile(0xc0007ae660, 0x23ce928, 0xc0008a45a0, 0xc0007a7930, 0xb, 0xc0007a7914, 0xb, 0xc0008a4500, 0x0, 0x0, ...)
        /workspace/controllers/kustomization_controller.go:245 +0xe58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0007a2460, 0x23ce928, 0xc0008a4510, 0xc0007a7930, 0xb, 0xc0007a7914, 0xb, 0xc0008a4500, 0x0, 0x0, ...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a2460, 0x23ce880, 0xc0007d5800, 0x1e4f660, 0xc000315b60)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a2460, 0x23ce880, 0xc0007d5800, 0x214b100)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000058d60, 0xc0007a2460, 0x23ce880, 0xc0007d5800)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
```
Flux version:
```bash
flux: v0.24.0
helm-controller: v0.14.0
image-automation-controller: v0.18.0
image-reflector-controller: v0.14.0
kustomize-controller: v0.18.1
notification-controller: v0.19.0
source-controller: v0.19.0
```

Tried:
Increasing resources(limits):
```yaml
 resources:
          limits:
            cpu: 2000m
            memory: 5Gi
          requests:
            cpu: 1000m
            memory: 4Gi
```
Also tried following flags:

```
 - args:
        - --events-addr=http://notification-controller.flux-system.svc.cluster.local/
        - --watch-all-namespaces=true
        - --log-level=debug
        - --log-encoding=json
        - --enable-leader-election
        - --concurrent=1
```

**Comment by stefanprodan** [comment]
One of your YAML files is malformed and this makes the kustomize/kyaml panic. To determine which file is causing this, run `kustomize build .` locally using kustomize v4.4.1. Please open an issue on the [kustomize](https://github.com/kubernetes-sigs/kustomize) repo, their forked version of go-yaml seems to have a major bug.

**Comment by hiddeco** [comment]
This seems to be related to https://github.com/go-yaml/yaml/issues/768

**Comment by gitbluf** [comment]
Managed to track down the malformed manifest as suggested by @stefanprodan.

Thanks guys for fast response.
