### ISSUE TITLE
Controller crashes on kustomize error

### ISSUE THREAD

**Issue by jhenriquez-ax** [fluxcd/kustomize-controller#639]
```
panic: number of previous names, number of previous namespaces, number of previous kinds not equal

goroutine 469 [running]:
sigs.k8s.io/kustomize/api/resource.(*Resource).PrevIds(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/resource/resource.go:431
sigs.k8s.io/kustomize/api/resource.(*Resource).OrgId(0xc0006f6000)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/resource/resource.go:414 +0x154
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).determineFilters(0xc002871920, {0xc001affbd8, 0x3, 0xc000e8b320})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/accumulator/namereferencetransformer.go:120 +0x89
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc0001a7950, {0x229df80, 0xc001e50288})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/accumulator/namereferencetransformer.go:52 +0x5d
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/accumulator/resaccumulator.go:142
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/accumulator/resaccumulator.go:168 +0xc5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0003aa0a0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/target/kusttarget.go:143 +0x8f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/internal/target/kusttarget.go:119
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0028720f8, {0x227f1c0, 0xc000d2a640}, {0xc000c440a0, 0x4a})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.4/krusty/kustomizer.go:89 +0x39c
github.com/fluxcd/kustomize-controller/controllers.secureBuildKustomization({0xc000c62080, 0xc000c440a0}, {0xc000c440a0, 0x4a})
        /workspace/controllers/kustomization_generator.go:268 +0x1e5
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).build(_, {_, _}, {_, _}, {{{0x1a7f1e3, 0xd}, {0xc000e14ae0, 0x23}}, {{0xc000795098, ...}, ...}, ...}, ...)
        /workspace/controllers/kustomization_controller.go:658 +0x227
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).reconcile(_, {_, _}, {{{0x1a7f1e3, 0xd}, {0xc000e14ae0, 0x23}}, {{0xc000795098, 0x12}, {0x0, ...}, ...}, ...}, ...)
        /workspace/controllers/kustomization_controller.go:375 +0x930
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).Reconcile(0xc0005603c0, {0x22336a8, 0xc000f27e90}, {{{0xc000e0d700, 0x1db7ca0}, {0xc000795098, 0x30}}})
        /workspace/controllers/kustomization_controller.go:268 +0x17ac
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0001e38c0, {0x22336a8, 0xc000f27e00}, {{{0xc000e0d700, 0x1db7ca0}, {0xc000795098, 0x413df4}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001e38c0, {0x2233600, 0xc000732500}, {0x1c93820, 0xc00037a400})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001e38c0, {0x2233600, 0xc000732500})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357
```

This particular error was because I encrypted a secret completely, including the name and kind. This error happens if one were to use kustomize directly.

It would be an improvement if the controller wouldn't crash. Providing a hint as to what file it was trying to process would be ideal.

**Comment by hiddeco** [comment]
Addressed via #673.
